title: "[Feature Request]: "
labels: [feature request]

body:
  - type: markdown
    attributes:
      value: |
        Note: Search to make sure you aren't suggesting a duplicate feature.
        
        You can include screen-shots or gif examples of what you want to achieve.
  - type: dropdown
    id: project
    attributes:
      label: Project
      description: Which project is this for?
      options:
        - Quill
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the feature is.
    validations:
      required: true
