title: "[Support]: "
labels: [support]

body:
  - type: markdown
    attributes:
      value: |
        Note: Search to make sure that your question wasn't asked before.
        
        You can include screen-shots or gifs.
  - type: dropdown
    id: plugin
    attributes:
      label: Project
      description: Which project are you asking for support about?
      options:
        - Quill
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the you need help with.
    validations:
      required: true
